language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install python-coveralls
  - mkdir -p ${HOME}/.abinit/abipy 
  - cp /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/abipy/data/managers/travis_manager.yml ${HOME}/.abinit/abipy/manager.yml
before_script:
  - python setup.py develop
script:
  - nosetests --nocapture
after_success:
  - coveralls
deploy:
  provider: pypi
  user: cicciopasticciotto
  distributions: sdist bdist_wheel
  on:
    tags: true
addons:
  apt:
    packages:
      - dvipng
      - texlive-fonts-recommended
      - texlive-latex-base
      - texlive-latex-extra
      
